version: '3.8'

services:
  nestjs_app_a:
    build: .
    ports:
      - 3000:3000
    command: sh -c "apt-get update && apt-get -y install chromium && npm run start:prod "
    restart: unless-stopped
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - NODE_ENV=production
